import { Game, Category, Proposal, Poll, Announcement } from '../types';

export const INITIAL_CATEGORIES: Category[] = [
  { id: 'sin-categoria', name: 'Sin categoría', icon: 'FolderQuestion', order: 0, description: 'Juegos nuevos pendientes de clasificar' },
  { id: 'arcade', name: 'Arcade', icon: 'Gamepad2', order: 1, description: 'Juegos clásicos, reflejos rápidos y diversión directa' },
  { id: 'accion', name: 'Acción', icon: 'Sword', order: 2, description: 'Combates, disparos, esquives y adrenalina pura' },
  { id: 'aventura', name: 'Aventura', icon: 'Compass', order: 3, description: 'Exploración de mundos misteriosos e historias' },
  { id: 'puzzle', name: 'Puzzle', icon: 'Puzzle', order: 4, description: 'Rompecabezas, acertijos y desafíos lógicos' },
  { id: 'carreras', name: 'Carreras', icon: 'Trophy', order: 5, description: 'Velocidad en pistas futuristas y circuitos salvajes' },
  { id: 'casual', name: 'Casual', icon: 'Smile', order: 6, description: 'Partidas rápidas, relajantes y para todo público' },
  { id: 'animales', name: 'Animales', icon: 'Cat', order: 7, description: 'Aventuras con simpáticas mascotas y fauna heroica' },
  { id: 'estrategia', name: 'Estrategia', icon: 'Crown', order: 8, description: 'Tácticas, gestión y defensa de reinos' },
  { id: 'otros', name: 'Otros', icon: 'Sparkles', order: 9, description: 'Prototipos innovadores y géneros experimentales' },
];

export const INITIAL_GAMES: Game[] = [
  {
    id: 'fox-thief',
    gameId: 'fox-thief',
    name: 'FOX THIEF',
    tagline: '¡Ayuda al astuto zorrito a infiltrarse en la granja y recolectar los huevos dorados!',
    description:
      'Un juego de sigilo y velocidad donde controlas a un carismático zorro en una misión nocturna. Esquiva a los perros guardianes, desactiva trampas ruidosas y consigue los legendarios huevos dorados antes de que amanezca.',
    howToPlay:
      '1. Usa las flechas del teclado o desliza en tu celular para mover al zorro.\n2. Recolecta todos los huevos dorados 🥚 repartidos en el escenario.\n3. Evita entrar en el cono de visión rojo de los perros guardianes 🐕.\n4. Cuando tengas todos los huevos, escapa rápidamente por la puerta 🚪.',
    mainImage: 'https://images.unsplash.com/photo-1516934024742-b461fba47600?w=800&auto=format&fit=crop&q=80',
    bannerImage: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?w=1600&auto=format&fit=crop&q=80',
    category: 'Animales',
    tags: ['Sigilo', 'Arcade', 'Zorro', 'Top Ranking', 'Multinivel'],
    status: 'PUBLICADO',
    webUrl: 'https://anapse.github.io/fox-thief/',
    embedAllowed: true,
    isNew: false,
    repository: {
      provider: 'github',
      owner: 'anapse',
      name: 'fox-thief',
      branch: 'main',
      url: 'https://github.com/anapse/fox-thief',
      lastSync: new Date().toISOString(),
    },
    firebaseConfig: {
      projectId: 'fox-thief-prod',
      databaseType: 'firestore',
      collections: {
        players: 'players',
        ranking: 'rankings',
        scores: 'scores',
        events: 'gameEvents',
      },
    },
    version: '1.2.4',
    platforms: ['Web', 'Android', 'iOS', 'Windows', 'Mac'],
    featured: true,
    inPromotion: true,
    visible: true,
    likesCount: 1248,
    playsCount: 18542,
    viewsCount: 34290,
    ratingAvg: 4.9,
    ratingsCount: 382,
    rankingConfig: {
      enabled: true,
      type: 'score',
      scoreField: 'score',
      order: 'desc',
      limit: 50,
      unit: 'pts',
    },
    sampleLeaderboard: [
      { rank: 1, playerName: 'ShadowFox_99', score: 28450, date: '2026-10-02' },
      { rank: 2, playerName: 'CyberRaccoon', score: 24120, date: '2026-10-01' },
      { rank: 3, playerName: 'NightStalker_PE', score: 21800, date: '2026-09-30' },
      { rank: 4, playerName: 'Valeria_Gamer', score: 19540, date: '2026-09-29' },
      { rank: 5, playerName: 'AlexTurbo', score: 17200, date: '2026-09-28' },
    ],
    createdAt: '2026-01-15T00:00:00Z',
  },
  {
    id: 'crazy-monkey-balloons',
    gameId: 'crazy-monkey-balloons',
    name: 'CRAZY MONKEY BALLOONS',
    tagline: '¡El mono travieso y su cañón de burbujas en una fiesta de globos flotantes!',
    description:
      'Un juego arcade vibrante y colorido. Apunta tu cañón, combina globos del mismo color y desata combos explosivos de frutas antes de que la pantalla se llene.',
    howToPlay:
      '1. Toca o haz clic para apuntar y disparar globos con el cañón.\n2. Junta 3 o más globos del mismo color para reventarlos.\n3. Recoge plátanos y frutas especiales para activar superpoderes.',
    mainImage: 'https://images.unsplash.com/photo-1540573133985-87b6da6d54a9?w=800&auto=format&fit=crop&q=80',
    bannerImage: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=1600&auto=format&fit=crop&q=80',
    category: 'Arcade',
    tags: ['Globos', 'Combos', 'Casual', 'Colorido'],
    status: 'PUBLICADO',
    webUrl: 'https://anapse.github.io/crazy-monkey-balloons/',
    embedAllowed: true,
    isNew: true,
    repository: {
      provider: 'github',
      owner: 'anapse',
      name: 'crazy-monkey-balloons',
      branch: 'main',
      url: 'https://github.com/anapse/crazy-monkey-balloons',
      lastSync: new Date().toISOString(),
    },
    firebaseConfig: {
      projectId: 'crazy-monkey-prod',
      databaseType: 'firestore',
      collections: {
        players: 'players',
        ranking: 'highscores',
        scores: 'scores',
      },
    },
    version: '1.0.8',
    platforms: ['Web', 'Android', 'iOS'],
    featured: false,
    inPromotion: false,
    visible: true,
    likesCount: 890,
    playsCount: 11200,
    viewsCount: 22100,
    ratingAvg: 4.7,
    ratingsCount: 215,
    rankingConfig: {
      enabled: true,
      type: 'score',
      scoreField: 'score',
      order: 'desc',
      limit: 50,
      unit: 'pts',
    },
    sampleLeaderboard: [
      { rank: 1, playerName: 'BananaKing', score: 45890, date: '2026-10-02' },
      { rank: 2, playerName: 'BalloonMaster', score: 39400, date: '2026-10-01' },
      { rank: 3, playerName: 'CocoLoco', score: 33210, date: '2026-09-30' },
    ],
    createdAt: '2026-02-10T00:00:00Z',
  },
  {
    id: 'fantastic-runner',
    gameId: 'fantastic-runner',
    name: 'FANTASTIC RUNNER: NEON CITY',
    tagline: 'Corre por los rascacielos neón a toda velocidad esquivando drones de vigilancia.',
    description:
      'Un infinite runner futurista lleno de saltos acrobáticos sobre rieles de luz, deslizamientos cibernéticos y coleccionables de energía.',
    howToPlay:
      '1. Desliza hacia arriba para saltar obstáculos y hacia abajo para deslizarte.\n2. Cambia de carril para recolectar baterías de energía.\n3. Activa el escudo magnético para atraer monedas.',
    mainImage: 'https://images.unsplash.com/photo-1551103782-8ab07afd45c1?w=800&auto=format&fit=crop&q=80',
    bannerImage: 'https://images.unsplash.com/photo-1511512578047-dfb367046420?w=1600&auto=format&fit=crop&q=80',
    category: 'Acción',
    tags: ['Runner', 'Cyberpunk', 'Velocidad', 'Neón'],
    status: 'BETA',
    webUrl: 'https://anapse.github.io/fantastic-runner/',
    embedAllowed: true,
    isNew: true,
    repository: {
      provider: 'github',
      owner: 'anapse',
      name: 'fantastic-runner',
      branch: 'develop',
      url: 'https://github.com/anapse/fantastic-runner',
    },
    version: '0.9.3-beta',
    platforms: ['Web', 'Android', 'Windows'],
    featured: false,
    inPromotion: true,
    visible: true,
    likesCount: 654,
    playsCount: 6420,
    viewsCount: 14500,
    ratingAvg: 4.6,
    ratingsCount: 140,
    rankingConfig: {
      enabled: true,
      type: 'distance',
      scoreField: 'meters',
      order: 'desc',
      limit: 100,
      unit: 'm',
    },
    sampleLeaderboard: [
      { rank: 1, playerName: 'SpeedDemon_2077', score: 8420, date: '2026-10-01' },
      { rank: 2, playerName: 'NeonRunner', score: 7850, date: '2026-09-29' },
    ],
    createdAt: '2026-03-01T00:00:00Z',
  },
  {
    id: 'gearpunk',
    gameId: 'gearpunk',
    name: 'GEARPUNK: CLOCKWORK ODYSSEY',
    tagline: 'Estrategia y combate táctico en un universo steampunk impulsado por vapor y engranajes.',
    description:
      'Construye tu automata de combate, ajusta engranajes de vapor y defiende la metrópolis flotante contra hordas de drones renegados.',
    howToPlay:
      '1. Coloca torres de vapor y autómatas en la cuadrícula táctica.\n2. Conecta las tuberías para bombear presión y multiplicar el daño.\n3. Mejora los núcleos de energía entre rondas.',
    mainImage: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=800&auto=format&fit=crop&q=80',
    category: 'Estrategia',
    tags: ['Steampunk', 'Táctico', 'Robots', 'Mechs'],
    status: 'EN CREACIÓN',
    webUrl: '',
    embedAllowed: false,
    isNew: false,
    repository: {
      provider: 'github',
      owner: 'anapse',
      name: 'gearpunk-odyssey',
      branch: 'main',
    },
    version: '0.4.1-alpha',
    platforms: ['Web', 'Windows', 'Mac'],
    featured: false,
    inPromotion: false,
    visible: true,
    likesCount: 420,
    playsCount: 0,
    viewsCount: 5200,
    ratingAvg: 0,
    ratingsCount: 0,
    createdAt: '2026-04-12T00:00:00Z',
  },
  {
    id: 'cyber-pixel-dungeon',
    gameId: 'cyber-pixel-dungeon',
    name: 'CYBER PIXEL DUNGEON',
    tagline: 'Mazmorras procedurales retro con magia hacker y chips legendarios.',
    description:
      'Un roguelike pixel-art clásico donde cada nivel se genera aleatoriamente. Hackea terminales, derrota jefes glitch y encuentra la placa madre sagrada.',
    howToPlay:
      '1. Explora piso por piso recolectando armas y chips de memoria.\n2. El combate es por turnos: cada paso que das, los enemigos se mueven.\n3. Hackea terminales para desbloquear atajos seguros.',
    mainImage: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=800&auto=format&fit=crop&q=80',
    category: 'Aventura',
    tags: ['Roguelike', 'Pixel Art', 'Mazmorras', 'Retro'],
    status: 'EN REPARACIÓN',
    webUrl: '',
    embedAllowed: false,
    isNew: false,
    version: '1.0.1-patch',
    platforms: ['Web', 'Android', 'Windows', 'Linux'],
    featured: false,
    inPromotion: false,
    visible: true,
    likesCount: 512,
    playsCount: 9400,
    viewsCount: 18200,
    ratingAvg: 4.8,
    ratingsCount: 198,
    rankingConfig: {
      enabled: true,
      type: 'level',
      scoreField: 'floor',
      order: 'desc',
      limit: 50,
      unit: 'Piso',
    },
    createdAt: '2026-01-20T00:00:00Z',
  },
  {
    id: 'astro-blaster-arena',
    gameId: 'astro-blaster-arena',
    name: 'ASTRO BLASTER ARENA',
    tagline: '¡Pilotea tu nave espacial en batallas estelares llenas de asteroides y rayos láser!',
    description:
      'Un shoot-em-up espacial hiper-rápido donde debes defender la estación orbital contra invasores del sector oscuro.',
    howToPlay:
      '1. Controla la nave espacial y dispara contra oleadas alienígenas.\n2. Esquiva los campos de asteroides y recolecta cristales de plasma.',
    mainImage: 'https://images.unsplash.com/photo-1614728894747-a83421e2b9c9?w=800&auto=format&fit=crop&q=80',
    category: 'Arcade',
    tags: ['Espacio', 'Naves', 'Láser', 'Retro'],
    status: 'PRÓXIMAMENTE',
    webUrl: '',
    embedAllowed: false,
    isNew: false,
    version: '0.1.0',
    platforms: ['Web', 'Android', 'iOS'],
    featured: false,
    inPromotion: false,
    visible: true,
    likesCount: 340,
    playsCount: 0,
    viewsCount: 4100,
    ratingAvg: 0,
    ratingsCount: 0,
    createdAt: '2026-05-01T00:00:00Z',
  },
];

export const INITIAL_PROPOSALS: Proposal[] = [
  {
    id: 'prop-cat-thief',
    title: '🐱 CAT THIEF: Misión Pescado Dorado',
    description: 'Un sigiloso gato ninja que debe infiltrarse en un mercado nocturno japonés para robar pescados frescos y salvar a su pandilla callejera.',
    category: 'Animales',
    idea: 'Controles táctiles fluidos para trepar techos, esconderse en cajas de cartón y distraer a los cocineros con maullidos.',
    imageUrl: 'https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?w=800&auto=format&fit=crop&q=80',
    authorId: 'user-carlos-12',
    authorName: 'Carlos M.',
    authorPhoto: 'https://api.dicebear.com/7.x/bottts/svg?seed=carlos',
    votesCount: 384,
    commentsCount: 42,
    status: 'IN_DEVELOPMENT',
    createdAt: '2026-03-10T10:00:00Z',
  },
  {
    id: 'prop-kart-pixel',
    title: '🏎️ SUPER PIXEL KART',
    description: 'Carreras multijugador retro con karts modificables, poderes de cáscaras electromagnéticas y pistas flotantes con gravedad cero.',
    category: 'Carreras',
    idea: 'Modo torneo semanal con ranking y fantasmas de otros jugadores.',
    imageUrl: 'https://images.unsplash.com/photo-1511512578047-dfb367046420?w=800&auto=format&fit=crop&q=80',
    authorId: 'user-maria-99',
    authorName: 'María Gamer',
    authorPhoto: 'https://api.dicebear.com/7.x/bottts/svg?seed=maria',
    votesCount: 295,
    commentsCount: 28,
    status: 'APPROVED',
    createdAt: '2026-03-18T14:30:00Z',
  },
  {
    id: 'prop-mini-golf',
    title: '🏌️ NEON MINI GOLF 3D',
    description: 'Campos de mini golf futuristas con portales dimensionales, aceleradores láser y física de rebote estilo pinball.',
    category: 'Casual',
    idea: 'Editor de pistas para que la comunidad cree y comparta sus propios hoyos.',
    imageUrl: 'https://images.unsplash.com/photo-1535131749006-b7f58c99034b?w=800&auto=format&fit=crop&q=80',
    authorId: 'user-juan-44',
    authorName: 'Juan P.',
    authorPhoto: 'https://api.dicebear.com/7.x/bottts/svg?seed=juan',
    votesCount: 182,
    commentsCount: 16,
    status: 'PENDING',
    createdAt: '2026-04-01T09:15:00Z',
  },
];

export const INITIAL_POLLS: Poll[] = [
  {
    id: 'poll-next-game-2026',
    question: '¿Qué juego hacemos después?',
    description: 'Vota directamente para elegir el próximo juego en desarrollo oficial de ANAPSE.',
    options: [
      { text: '🏎️ Carrera de motos', votes: 420, icon: 'Flame' },
      { text: '🐱 Cat Thief', votes: 310, icon: 'Cat' },
      { text: '🏌️ Mini Golf 3D', votes: 270, icon: 'Sparkles' },
    ],
    active: true,
    totalVotes: 1000,
    expiresAt: '2026-11-01T00:00:00Z',
    createdAt: '2026-03-01T00:00:00Z',
  },
];

export const INITIAL_ANNOUNCEMENTS: Announcement[] = [
  {
    id: 'ann-welcome',
    title: '🎉 ¡Bienvenidos a ANAPSE VIDEO GAMES!',
    content: 'Juegos gratis para jugar y compartir desde tu navegador o celular.',
    type: 'release',
    actionLabel: 'Ver Juegos',
    actionUrl: '#games-section',
    active: true,
    createdAt: new Date().toISOString(),
  },
];
